/* Copyright Ultramarine Holdings LLC - All Rights Reserved
 * -------------------------------------------
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited.
 * Proprietary and Confidential.
 *
 *
 *
 * Written By Raptor Network <client-development@raptor.network>, May 2021
 */

#include "assert.h"
#include "hardware_id.h"
#include "scope_exit.h"

#include <cstdio>
#include <random>
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/entropy.h>

#ifdef _WIN32
#include <windows.h>
#endif

namespace Common {

namespace {

constexpr const char INVALID[] = "RAPTOR-NETWORK-CITRUS-INVALID-HWID";
constexpr const char KEY[] = R"(SOFTWARE\Ultramarine\RaptorNetwork\Citrus)";
constexpr const char VALUE[] = "HardwareID";
constexpr const char ALPHABET[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
constexpr std::size_t ID_LENGTH = 0x30;

std::string GenerateID() {
    mbedtls_entropy_context entropy;
    mbedtls_entropy_init(&entropy);
    mbedtls_ctr_drbg_context ctr_drbg;
    constexpr std::array<char, 27> personalization{{"RaptorCitrus Hardware ID 1"}};

    mbedtls_ctr_drbg_init(&ctr_drbg);
    if (mbedtls_ctr_drbg_seed(&ctr_drbg, mbedtls_entropy_func, &entropy,
                              reinterpret_cast<const unsigned char*>(personalization.data()),
                              personalization.size()) != 0) {
        mbedtls_ctr_drbg_free(&ctr_drbg);
        mbedtls_entropy_free(&entropy);
        return INVALID;
    }

    std::string new_id(ID_LENGTH, '\0');
    u32 value{};
    for (char& i : new_id) {
        if (mbedtls_ctr_drbg_random(&ctr_drbg, reinterpret_cast<unsigned char*>(&value),
                                    sizeof(u32)) != 0) {
            mbedtls_ctr_drbg_free(&ctr_drbg);
            mbedtls_entropy_free(&entropy);
            return INVALID;
        }
        i = ALPHABET[value % 62];
    }

    mbedtls_ctr_drbg_free(&ctr_drbg);
    mbedtls_entropy_free(&entropy);
    return new_id;
}

} // namespace

#ifdef _WIN32

namespace {

std::string GetRaptorHardwareIDImpl() {
    HKEY key{};
    if (RegCreateKeyA(HKEY_CURRENT_USER, KEY, &key) != ERROR_SUCCESS) {
        return INVALID;
    }
    SCOPE_EXIT({ RegCloseKey(key); });

    DWORD data_size{};
    const auto res1 =
        RegGetValueA(key, nullptr, VALUE, RRF_RT_REG_SZ, nullptr, nullptr, &data_size);
    if (res1 != ERROR_SUCCESS || data_size < (ID_LENGTH + 1)) {
        auto new_id = GenerateID();
        if (RegSetKeyValueA(key, nullptr, VALUE, REG_SZ, new_id.c_str(),
                            static_cast<DWORD>(new_id.size())) == ERROR_SUCCESS) {
            return new_id;
        } else {
            return INVALID;
        }
    }

    std::string out(data_size, '\0');
    if (RegGetValueA(key, nullptr, VALUE, RRF_RT_REG_SZ, nullptr, out.data(), &data_size) !=
        ERROR_SUCCESS) {
        return INVALID;
    }

    out.resize(data_size - 1);
    return out;
}

} // namespace

#elif defined(__linux__)

namespace {

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-result"

std::string GetRaptorHardwareIDImpl() {
    static constexpr const char INFO_TEXT[] =
        "\n\n# DO NOT EDIT - FILE AUTOMATICALLY GENERATED BY RAPTOR CITRUS\n# THIS ID IS USED TO "
        "SECURE YOUR ACCOUNT\n# PLEASE DO NOT EDIT OR DELETE THIS FILE - MAY REQUIRE YOU TO LOGIN "
        "AGAIN\n";

    auto* file = std::fopen("~/.raptor_id", "r+");
    if (file == nullptr) {
        auto* write = std::fopen("~/.raptor_id", "w+");
        if (write == nullptr) {
            return INVALID;
        }

        auto new_id = GenerateID();
        std::fputs(new_id.c_str(), write);
        std::fputs(INFO_TEXT, write);
        std::fclose(write);
        return new_id;
    }

    std::fseek(file, 0, SEEK_END);
    const auto size = std::ftell(file);
    if (static_cast<unsigned long>(size) < ID_LENGTH) {
        return INVALID;
    }

    std::string out(ID_LENGTH, '\0');
    std::fread(out.data(), 1, out.size(), file);
    std::fclose(file);
    return out;
}

#pragma GCC diagnostic pop

} // namespace

#else

static_assert(false, "No Raptor Hardware ID Implementation for Platform");

#endif

const std::string& GetRaptorHardwareID() {
    static const auto id = GetRaptorHardwareIDImpl();
    return id;
}

} // namespace Common
